samples: ['100V_post', '100V_pre', '102V_post', '102V_pre', '103V_post',
 '103V_pre', '104V_post', '104V_pre', '105V_post', '105V_pre', '106V_post',
 '106V_pre', '107V_post', '107V_pre', '108V_post', '108V_pre', '109V_post',
 '109V_pre', '110V_post', '110V_pre', '111V_post', '111V_pre', '112V_post',
 '112V_pre', '113V_post', '113V_pre', '114V_post', '114V_pre', '115V_post',
 '115V_pre', '116V_post', '116V_pre', '118V_post', '118V_pre', '120V_post',
 '120V_pre', '122V_post', '122V_pre', '123V_post', '123V_pre', '124V_post',
 '124V_pre', '125V_post', '125V_pre', '126V_post', '126V_pre', '127V_post',
 '127V_pre', '129V_post', '129V_pre', '12V_post', '12V_pre', '130V_post',
 '130V_pre', '132V_post', '132V_pre', '133V_post', '133V_pre', '135V_post',
 '135V_pre', '136V_post', '136V_pre', '137V_post', '137V_pre', '138V_post',
 '138V_pre', '139V_post', '139V_pre', '13V_post', '13V_pre', '140V_post',
 '140V_pre', '141V_post', '141V_pre', '142V_post', '142V_pre', '143V_post', '143V_pre', '144V_post',
 '144V_pre', '145V_post', '145V_pre', '147V_pre', '149V_post', '149V_pre', '14V_post', '14V_pre', '150V_post',
 '150V_pre', '151V_post', '151V_pre', '152V_post', '152V_pre', '153V_post',
 '153V_pre', '154V_post', '154V_pre', '155V_pre', '156V_post', '156V_pre', '157V_post',
 '157V_pre', '159V_post', '159V_pre', '160V_post', '160V_pre', '161V_post', '161V_pre', '162V_post',
 '162V_pre', '163V_post', '163V_pre', '164V_post', '164V_pre', '16V_post', '17V_post',
 '17V_pre', '19V_post', '19V_pre', '20V_post', '20V_pre', '21V_post', '21V_pre',
 '23V_post', '23V_pre', '24V_post', '24V_pre', '28V_post', '28V_pre', '29V_post',
 '29V_pre', '2V_post', '2V_pre', '30V_post', '30V_pre', '31V_post', '31V_pre',
 '32V_post', '32V_pre', '33V_post', '33V_pre', '34V_post', '34V_pre', '35V_post',
 '35V_pre', '36V_pre', '3V_post', '3V_pre', '41V_post', '41V_pre', '42V_post',
 '42V_pre', '44V_post', '44V_pre', '46V_post', '46V_pre', '47V_post', '47V_pre',
 '48V_post', '48V_pre', '49V_post', '49V_pre', '50V_post', '50V_pre', '51V_post',
 '51V_pre', '52V_post', '52V_pre', '54V_post', '54V_pre', '55V_post', '55V_pre',
 '56V_post', '56V_pre', '57V_post', '57V_pre', '59V_post', '59V_pre', '60V_post',
 '60V_pre', '61V_post', '61V_pre', '62V_post', '62V_pre', '63V_post', '63V_pre',
 '64V_post', '64V_pre', '65V_post', '65V_pre', '66V_post', '66V_pre', '67V_post', '67V_pre',
 '68V_post', '68V_pre', '69V_post', '69V_pre', '70V_post', '70V_pre', '71V_post',
 '71V_pre', '73V_post', '73V_pre', '74V_post', '74V_pre', '76V_post', '76V_pre',
 '78V_post', '78V_pre', '79V_post', '79V_pre', '80V_post', '80V_pre', '81V_post',
 '81V_pre', '82V_post', '82V_pre', '84V_post', '84V_pre', '86V_post', '86V_pre',
 '88V_post', '88V_pre', '89V_post', '89V_pre', '8V_post', '8V_pre', '90V_post',
 '90V_pre', '92V_post', '92V_pre', '93V_post', '93V_pre', '95V_post', '95V_pre',
 '96V_post', '96V_pre', '98V_post', '98V_pre', '99V_post', '99V_pre', '9V_post', '9V_pre'
 ]

# samples: [ '16V_post', '17V_post',
#  '17V_pre', '19V_post', '19V_pre', '20V_post', '20V_pre', '21V_post', '21V_pre',
#  '23V_post', '23V_pre', '24V_post', '24V_pre', '28V_post', '28V_pre', '29V_post',
#  '29V_pre', '2V_post', '2V_pre', '30V_post', '30V_pre', '31V_post', '31V_pre',
#  '32V_post', '32V_pre', '33V_post', '33V_pre', '34V_post', '34V_pre', '35V_post',
#  '35V_pre', '36V_pre', '3V_post', '3V_pre', '41V_post', '41V_pre', '42V_post',
#  '42V_pre', '44V_post', '44V_pre', '46V_post', '46V_pre', '47V_post', '47V_pre',
#  '48V_post', '48V_pre', '49V_post', '49V_pre', '50V_post', '50V_pre', '51V_post',
#  '51V_pre', '52V_post', '52V_pre', '54V_post', '54V_pre', '55V_post', '55V_pre',
#  '56V_post', '56V_pre', '57V_post', '57V_pre', '59V_post', '59V_pre', '60V_post',
#  '60V_pre', '61V_post', '61V_pre', '62V_post', '62V_pre', '63V_post', '63V_pre',
#  '64V_post', '64V_pre', '65V_post', '65V_pre', '66V_post', '66V_pre', '67V_post', '67V_pre',
#  '68V_post', '68V_pre', '69V_post', '69V_pre', '70V_post', '70V_pre', '71V_post',
#  '71V_pre', '73V_post', '73V_pre', '74V_post', '74V_pre', '76V_post', '76V_pre',
#  '78V_post', '78V_pre', '79V_post', '79V_pre', '80V_post', '80V_pre', '81V_post',
#  '81V_pre', '82V_post', '82V_pre', '84V_post', '84V_pre', '86V_post', '86V_pre',
#  '88V_post', '88V_pre', '89V_post', '89V_pre', '8V_post', '8V_pre', '90V_post',
#  '90V_pre', '92V_post', '92V_pre', '93V_post', '93V_pre', '95V_post', '95V_pre',
#  '96V_post', '96V_pre', '98V_post', '98V_pre', '99V_post', '99V_pre', '9V_post', '9V_pre'
#  ]

genome: GRCh38
kallisto_idx: /home/wdeng3/workspace/Codespace/universal_data/ref/GRCh38/gencode.v44.transcripts.kallisto.idx
star_idx: /home/wdeng3/workspace/Codespace/universal_data/ref/GRCh38/STAR